config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

    resources :topics do

        resources :comments
        post :confirm, on: :collection

    end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, only: [:index,:show]
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only:[:edit,:update,:destroy,:show]


  def create
      @comment = current_user.comments.build(comments_params)
      @topic = @comment.topic

      respond_to do |format|
        if @comment.save
          format.html {redirect_to topic_path(@topic),notice: 'コメントを投稿しました！'}
          format.js {render :index}
        else
          format.html {render :new}
        end
      end
  end

  def edit
  end

  def update
      @comment = Comment.find(params[:id])
      if @comment.update(comments_params)
        redirect_to topic_path(@comment.topic), notice:"コメントが編集されました!"
      else
        redirect_to edit_topic_comment_path, notice:"コメントを編集してください!"
      end
  end


  def destroy
    @comment=Comment.find(params[:id])
    flash[:notice] = 'コメントを削除しました。'
    respond_to do |format|
          @comment.destroy
           format.js { render :index }
    end
  end

  private

    def comments_params
      params.require(:comment).permit(:topic_id, :content)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true) do |f| %>

  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_topic_comment_path(topic,comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class = "container-fluid">
  <div class = "wrapper col-md-8 col-md-offset-2 col-sm-10" >

<%= form_for [@comment.topic, @comment] do |f| %>
   <%=f.label :コメント%>
   <%=f.text_field :content, class:'form-control'%>
   <br>
   <%=f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>


</div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')