config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

    resources :topics do

        resources :comments
        post :confirm, on: :collection

    end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, only: [:index,:show]
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

before_action :authenticate_user!
before_action :set_topic, only:[:edit,:update,:destroy,:show]

  def index
    @topics = Topic.all
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topic = Topic.create(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice:"投稿しました！"
      NoticeMailer.sendmail_topic(@topic).deliver
    else
      render 'new', notice:"投稿内容がありません。"
    end
  end

  def confirm
    @topic = Topic.new(topics_params)
    render :new if @topic.invalid?
  end

  def edit
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  def update
    @topic.update(topics_params)
    if @topic.save
      redirect_to topics_path,notice:"投稿を更新しました！"
    else
      render 'edit',notice:"投稿内容がありません。"
    end

  end

  def destroy
    @topic.destroy
    redirect_to topics_path,notice:"ブログを削除しました！"
  end

private
  def topics_params
    params.require(:topic).permit(:content)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_topics_path
    elsif action_name == 'edit'
      topic_path
    end
  end
  
end

app/views/topics/_form.html.erb
      <%= form_for(@topic,url: choose_new_or_edit) do |f| %>
        <%if @topic.errors.any? %>
          <div id="error_explanation">
            <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

            <ul>
            <% @topic.errors.full_messages.each do|msg|%>
              <li><%=msg%></li>
            <%end%>
            </ul>
          </div>
        <%end%>

        <%= f.label :投稿内容 %>
        <%= f.text_field :content, class:'form-control' %>
        <br>
        <%= f.submit '投稿', class:'btn btn-primary btn-block' %>
      <% end %>
      <br>
      <%= link_to "投稿一覧画面にもどる", topics_path, class: 'btn btn-default btn-block' %>

app/views/topics/confirm.html.erb
<h3>以下の内容で送信する</h3>

<%= form_for(@topic)do |f| %>
  <%= f.hidden_field :content %>

  <p>投稿内容：<%=@topic.content %>
  <br>
  <%= f.submit "投稿する" %>

<% end %>

<%= form_for(@topic, url: new_topic_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name:'back' %>
<% end %>

app/views/topics/edit.html.erb
<div class = "container-fluid">
  <div class = "wrapper col-md-8 col-md-offset-2 col-sm-10" >

    <h2>投稿を編集する</h2>
    <%= render 'form' %>

  </div>
</div>

app/views/topics/index.html.erb
<div class = "container-fluid">
  <div class = "wrapper col-md-8 col-md-offset-2 col-sm-10" >

    <p><%= notice %></p>
    <h1>投稿一覧</h1>
    <%= link_to "新しく投稿する", new_topic_path, class:'btn btn-default' %>

    <br>
    <br>

    <% @topics.each do |topic| %>
      <div class="row">
        <%= link_to topic_path(topic) do %>
          <h4><strong><%= topic.content %></strong></h4>
        <% end %>
        <br>
        <p>投稿者：<%= User.find(topic.user_id).name %></p>
        <%= link_to "編集する", edit_topic_path(topic.id), class: 'btn btn-default btn-small btn-success' %>
        <%= link_to "削除する", topic_path(topic.id), method: :delete, data: {confirm: '本当に削除してよいですか？'}, class:"btn btn-default btn-small btn-danger" %>
      </div>
    <% end %>

  </div>
</div>

app/views/topics/new.html.erb
<div class = "container-fluid">
  <div class = "wrapper col-md-8 col-md-offset-2 col-sm-10" >

    <h2>投稿する</h2>
    <%= render 'form' %>

  </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="blog-text">
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @topic.content %>
      <% if current_user.id == @topic.user_id %>
      <br>
        <%= link_to '編集', edit_topic_path(@topic) %>
      <% end %>
      </p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>

    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <%= link_to '戻る', topics_path %>

  </div>
</div>