config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

    resources :topics do

        resources :comments
        post :confirm, on: :collection

    end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, only: [:index,:show]
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship",  dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader #deviseの設定配下に追記

   def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
     user = User.find_by(provider: auth.provider, uid: auth.uid)

     unless user
       user = User.new(
           name:     auth.extra.raw_info.name,
           provider: auth.provider,
           uid:      auth.uid,
           email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
           image_url:   auth.info.image,
           password: Devise.friendly_token[0, 20]
       )
       user.skip_confirmation!
       user.save(validate: false)
      end
     user
   end

   def facebook
     # You need to implement the method below in your model (e.g. app/models/user.rb)
     @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

     if @user.persisted?
       set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
       sign_in_and_redirect @user, event: :authentication
     else
       session["devise.facebook_data"] = request.env["omniauth.auth"]
       redirect_to new_user_registration_url
     end
   end

   def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
     end
    user
   end

   def self.create_unique_string
       SecureRandom.uuid
     end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

    #指定のユーザをフォローする
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  #フォローしているかどうかを確認する
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

   def facebook
     # You need to implement the method below in your model (e.g. app/models/user.rb)
     @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

     if @user.persisted?
       set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
       sign_in_and_redirect @user, event: :authentication
     else
       session["devise.facebook_data"] = request.env["omniauth.auth"]
       redirect_to new_user_registration_url
     end
   end

   def twitter
     # You need to implement the method below in your model
     @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

     if @user.persisted?
       set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
       sign_in_and_redirect @user, event: :authentication
     else
       session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
       redirect_to new_user_registration_url
     end
   end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    #選択したユーザ
    @user = User.find(params[:id])
    #フォローワーとフォローしている人を調べるため
    @users=User.all
  end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registration_controller_helper.rb
module Users::RegistrationControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">

<% unless user == current_user %>
  <% unless current_user.following?(user)%>
    <%= form_for(current_user.relationships.build(followed_id: user.id),remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class:"btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "つながりを解除", class:"btn btn-large" %>
    <% end %>
  <% end %>
<% end %>
  <%= link_to "ユーザー詳細", user_path(user.id), class: 'btn btn-default btn-sm btn-success' %>


</div>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザー</h2>

        <% @users.each do |user| %>
            <% if user.id != current_user.id %>
            <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
                <div class="item">
                  <%= profile_img(user) %>
                  <%= user.email %>
                  <%= link_to user.name, user %>
                  <br>
                  <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
                  <%= render partial: 'follow_form', locals: { user: user } if signed_in?   %>
                </div>
            </div>
            <% end %>
      <% end %>
</div>

app/views/users/show.html.erb
<div class="container">


<h2>フォロー一覧</h2>

  <!--users全体を確認-->
  <% @users.each do |user| %>

  <!--選択されている@userがフォローしている人なら表示-->
    <% if @user.following?(user) %>
    <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
      <%= profile_img(user) %>
      <br>
      <%= user.name %>
    </div>
    <% end %>
  <% end %>

<div class="container-child col-md-12 col-sm-12 col-xs-12" >
<br>
<h2>フォローワー一覧</h2>
</div>
  <!--users全体を確認-->
  <% @users.each do |user| %>
  <!--選択されている@userをフォローしている人なら表示-->
    <% if user.following?(@user) %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
      <%= profile_img(user) %>
      <br>
      <%= user.name %>
      </div>
   <% end %>
  <% end %>



</div>