config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

    resources :topics do

        resources :comments
        post :confirm, on: :collection

    end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, only: [:index,:show]
  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebookdayo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <ul>
        <li><%= link_to "Facebookdayo", root_path%></a></li>
        <li><%= link_to "トップページ",root_path%></a></li>
        <li><%= link_to "投稿", topics_path%></a></li>
        <li><%= link_to 'ユーザー一覧', users_path if user_signed_in? %></li>
        <li><%= link_to "メッセージ", conversations_path %></li>

      <% if user_signed_in? %>
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
    </ul>
  </header>

<%= yield %>

  <footer>
    <p>Facebook@2017</p>
  </footer>

</body>
</html>